CREATE DATABASE IF NOT EXISTS parking_lot;
USE parking_lot;

DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS slots;

CREATE TABLE slots (
    id INT PRIMARY KEY AUTO_INCREMENT,
    slot_number INT NOT NULL,
    vehicle_type VARCHAR(10) NOT NULL,
    occupied BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE KEY unique_slot (slot_number, vehicle_type)
);

CREATE TABLE tickets (
    id INT PRIMARY KEY AUTO_INCREMENT,
    slot_id INT NOT NULL,
    vehicle_no VARCHAR(20) NOT NULL,
    vehicle_type VARCHAR(10) NOT NULL,
    entry_time DATETIME NOT NULL,
    exit_time DATETIME NULL,
    amount DECIMAL(10,2) NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (slot_id) REFERENCES slots(id)
);

-- CAR SLOTS (100 slots)
INSERT INTO slots (slot_number, vehicle_type, occupied) VALUES
(1,'CAR',FALSE),(2,'CAR',FALSE),(3,'CAR',FALSE),(4,'CAR',FALSE),(5,'CAR',FALSE),
(6,'CAR',FALSE),(7,'CAR',FALSE),(8,'CAR',FALSE),(9,'CAR',FALSE),(10,'CAR',FALSE),
(11,'CAR',FALSE),(12,'CAR',FALSE),(13,'CAR',FALSE),(14,'CAR',FALSE),(15,'CAR',FALSE),
(16,'CAR',FALSE),(17,'CAR',FALSE),(18,'CAR',FALSE),(19,'CAR',FALSE),(20,'CAR',FALSE),
(21,'CAR',FALSE),(22,'CAR',FALSE),(23,'CAR',FALSE),(24,'CAR',FALSE),(25,'CAR',FALSE),
(26,'CAR',FALSE),(27,'CAR',FALSE),(28,'CAR',FALSE),(29,'CAR',FALSE),(30,'CAR',FALSE),
(31,'CAR',FALSE),(32,'CAR',FALSE),(33,'CAR',FALSE),(34,'CAR',FALSE),(35,'CAR',FALSE),
(36,'CAR',FALSE),(37,'CAR',FALSE),(38,'CAR',FALSE),(39,'CAR',FALSE),(40,'CAR',FALSE),
(41,'CAR',FALSE),(42,'CAR',FALSE),(43,'CAR',FALSE),(44,'CAR',FALSE),(45,'CAR',FALSE),
(46,'CAR',FALSE),(47,'CAR',FALSE),(48,'CAR',FALSE),(49,'CAR',FALSE),(50,'CAR',FALSE),
(51,'CAR',FALSE),(52,'CAR',FALSE),(53,'CAR',FALSE),(54,'CAR',FALSE),(55,'CAR',FALSE),
(56,'CAR',FALSE),(57,'CAR',FALSE),(58,'CAR',FALSE),(59,'CAR',FALSE),(60,'CAR',FALSE),
(61,'CAR',FALSE),(62,'CAR',FALSE),(63,'CAR',FALSE),(64,'CAR',FALSE),(65,'CAR',FALSE),
(66,'CAR',FALSE),(67,'CAR',FALSE),(68,'CAR',FALSE),(69,'CAR',FALSE),(70,'CAR',FALSE),
(71,'CAR',FALSE),(72,'CAR',FALSE),(73,'CAR',FALSE),(74,'CAR',FALSE),(75,'CAR',FALSE),
(76,'CAR',FALSE),(77,'CAR',FALSE),(78,'CAR',FALSE),(79,'CAR',FALSE),(80,'CAR',FALSE),
(81,'CAR',FALSE),(82,'CAR',FALSE),(83,'CAR',FALSE),(84,'CAR',FALSE),(85,'CAR',FALSE),
(86,'CAR',FALSE),(87,'CAR',FALSE),(88,'CAR',FALSE),(89,'CAR',FALSE),(90,'CAR',FALSE),
(91,'CAR',FALSE),(92,'CAR',FALSE),(93,'CAR',FALSE),(94,'CAR',FALSE),(95,'CAR',FALSE),
(96,'CAR',FALSE),(97,'CAR',FALSE),(98,'CAR',FALSE),(99,'CAR',FALSE),(100,'CAR',FALSE);

-- BIKE SLOTS (50 slots)
INSERT INTO slots (slot_number, vehicle_type, occupied) VALUES
(1,'BIKE',FALSE),(2,'BIKE',FALSE),(3,'BIKE',FALSE),(4,'BIKE',FALSE),(5,'BIKE',FALSE),
(6,'BIKE',FALSE),(7,'BIKE',FALSE),(8,'BIKE',FALSE),(9,'BIKE',FALSE),(10,'BIKE',FALSE),
(11,'BIKE',FALSE),(12,'BIKE',FALSE),(13,'BIKE',FALSE),(14,'BIKE',FALSE),(15,'BIKE',FALSE),
(16,'BIKE',FALSE),(17,'BIKE',FALSE),(18,'BIKE',FALSE),(19,'BIKE',FALSE),(20,'BIKE',FALSE),
(21,'BIKE',FALSE),(22,'BIKE',FALSE),(23,'BIKE',FALSE),(24,'BIKE',FALSE),(25,'BIKE',FALSE),
(26,'BIKE',FALSE),(27,'BIKE',FALSE),(28,'BIKE',FALSE),(29,'BIKE',FALSE),(30,'BIKE',FALSE),
(31,'BIKE',FALSE),(32,'BIKE',FALSE),(33,'BIKE',FALSE),(34,'BIKE',FALSE),(35,'BIKE',FALSE),
(36,'BIKE',FALSE),(37,'BIKE',FALSE),(38,'BIKE',FALSE),(39,'BIKE',FALSE),(40,'BIKE',FALSE),
(41,'BIKE',FALSE),(42,'BIKE',FALSE),(43,'BIKE',FALSE),(44,'BIKE',FALSE),(45,'BIKE',FALSE),
(46,'BIKE',FALSE),(47,'BIKE',FALSE),(48,'BIKE',FALSE),(49,'BIKE',FALSE),(50,'BIKE',FALSE);
